fix: various informational issues
MZero-Labs/common pull request #17
Opened 2024-02-16 23:47 UTC by PierrickGT

Issues:
- Quantstamp MZ-21 Code Documentation
  -

2024-02-22 17:43 UTC, toninorair approved these changes

2024-02-22 19:30 UTC, deluca-mike requested changes

2024-02-22 19:30 UTC, deluca-mike commented on src/ERC712.sol
> +abstract contract ERC712 is IERC712, IERC5267 {
`ERC712` does not need `ERC5267`, but `ERC5267` needs `ERC712`, so this contract can no longer be called `ERC712`.

There needs to be an `IERC712`/`ERC712`, an `IERC5267`/`ERC5267`, and `ISomething`/`Something` that is both `ERC712` and `ERC5267`. Not sure what `Something` is, but for now, this contract implements more than `ERC712`, which is confusing and inaccurate.

2024-02-22 21:02 UTC, PierrickGT commented on src/ERC712.sol
> +abstract contract ERC712 is IERC712, IERC5267 {
Fixed: https://github.com/MZero-Labs/common/pull/17/commits/a296ca7f02e4b944381c9dd737594535fad24402

2024-02-23 17:12 UTC, deluca-mike approved these changes

2024-02-23 17:13 UTC, merged